/**
 * Deutsch → Englisch. Schluessel ist der deutsche Text, wie er im Code steht.
 *
 * Ohne "server-only": das Woerterbuch wird auch von Client-Komponenten
 * gebraucht (Navigation, Menueleiste), die ihre Sprache als Eigenschaft
 * bekommen.
 *
 * Was hier fehlt, erscheint auf Deutsch. Beim Ergaenzen den deutschen
 * Text genau so uebernehmen, wie er im Code steht - samt Umlauten,
 * Auslassungspunkten und Bindestrichen.
 */
export const WOERTERBUCH_EN: Record<string, string> = {
  // --- Navigation und Grundgeruest -----------------------------------------
  Übersicht: "Overview",
  Dashboard: "Dashboard",
  Belegungsplan: "Occupancy plan",
  Vermietung: "Letting",
  Objekte: "Properties",
  Mieter: "Tenants",
  Mietverträge: "Rental contracts",
  Buchhaltung: "Accounting",
  Buchungen: "Transactions",
  Kontoauszüge: "Bank statements",
  Mieteingänge: "Rent payments",
  Belege: "Receipts",
  "Offene Posten": "Open items",
  Steuerberater: "Tax advisor",
  System: "System",
  Einstellungen: "Settings",
  Abmelden: "Sign out",
  "Menü umschalten": "Toggle menu",
  "Zum Dashboard": "To the dashboard",
  Monteurunterkünfte: "Contractor accommodation",

  // --- Schwebende Menueleiste (Handy) --------------------------------------
  Belegung: "Occupancy",
  Mieten: "Rents",
  Schnellzugriff: "Quick access",
  "Schnell erledigen": "Quick actions",
  "Schnellaktionen öffnen": "Open quick actions",
  "Schnellaktionen schließen": "Close quick actions",
  "Beleg fotografieren": "Photograph receipt",
  "Quittung direkt mit der Kamera erfassen": "Capture a receipt with the camera",
  "Miete abhaken": "Tick off rent",
  "Eingegangene Mieten des Monats bestätigen": "Confirm this month's incoming rents",
  "Mieter anlegen": "Add tenant",
  "Neuer Monteur mit Bett und Vertrag": "New contractor with bed and contract",
  "Kontoauszug einlesen": "Import bank statement",
  "PDF oder CSV der Bank hochladen": "Upload a PDF or CSV from the bank",
  Schließen: "Close",

  // --- Anmeldung ------------------------------------------------------------
  Anmelden: "Sign in",
  "Verwaltung für Monteurunterkünfte": "Contractor accommodation management",
  "Bitte mit den Zugangsdaten der Hausverwaltung anmelden.":
    "Please sign in with the property management credentials.",
  "E-Mail-Adresse oder Passwort ist nicht korrekt.": "Email address or password is incorrect.",
  "Erste Anmeldung": "First sign-in",
  "Keine Datenbankverbindung": "No database connection",
  "E-Mail": "Email",
  Passwort: "Password",
  "Passwort anzeigen": "Show password",
  "Passwort verbergen": "Hide password",
  "Mieter benötigen keinen Zugang – sie erhalten einen persönlichen Vertragslink.":
    "Tenants do not need an account - they receive a personal contract link.",

  // --- Tickets ---------------------------------------------------------------
  Tickets: "Tickets",
  "Anliegen aus den Objekten: was kaputt ist, was fehlt, was jemand gemeldet hat.":
    "Issues from the properties: what is broken, what is missing, what someone reported.",
  "Ticket anlegen": "Create ticket",
  "Ticket bearbeiten": "Edit ticket",
  "Ticket löschen": "Delete ticket",
  "Ticket samt Verlauf und Anhängen löschen?": "Delete ticket including history and attachments?",
  "Ticket melden": "Report a ticket",
  "Schaden oder Anliegen mit Foto festhalten": "Record damage or an issue with a photo",
  "Keine Tickets": "No tickets",
  "Hier steht, was in den Objekten zu tun ist. Legen Sie das erste Anliegen an.":
    "This is where the work on your properties is listed. Create the first issue.",
  "Ein Satz genügt; Foto und Details sind freiwillig.":
    "One sentence is enough; photo and details are optional.",
  Anliegen: "Issue",
  Zuordnung: "Assignment",
  Beschreibung: "Description",
  "Keine weitere Beschreibung.": "No further description.",
  "z. B. Boiler in Bad 2 tropft": "e.g. boiler in bathroom 2 is dripping",
  "Was genau ist passiert? Seit wann? Wer hat es gemeldet?":
    "What exactly happened? Since when? Who reported it?",
  Dringlichkeit: "Priority",
  Niedrig: "Low",
  Normal: "Normal",
  Hoch: "High",
  Offen: "Open",
  "In Arbeit": "In progress",
  Erledigt: "Done",
  Aktuell: "Current",
  "Betroffenes Objekt": "Property concerned",
  "Betroffener Mieter": "Tenant concerned",
  "Kein Objekt": "No property",
  "Kein Mieter": "No tenant",
  Bearbeiter: "Assignee",
  "Wer kümmert sich?": "Who is taking care of it?",
  "Foto oder Dokument": "Photo or document",
  Verlauf: "History",
  "Wer hat was erledigt, wen angerufen, was vereinbart.":
    "Who did what, who was called, what was agreed.",
  "Noch keine Notizen.": "No notes yet.",
  "Notiz hinzufügen": "Add a note",
  "Notiz speichern": "Save note",
  "Was ist passiert?": "What happened?",
  Anhänge: "Attachments",
  Notizen: "notes",
  "Fotos vom Schaden, Kostenvoranschlag, Rechnung.": "Photos of the damage, quote, invoice.",
  "Noch keine Anhänge.": "No attachments yet.",
  "Anhang hinzufügen": "Add attachment",
  "Wieder öffnen": "Reopen",
  Auf: "Mark as",
  Angelegt: "Created",
  "Erledigt am": "Completed on",
  "Liegt seit": "Open for",
  Tagen: "days",
  Ehemalig: "Former",

  // --- Support-Meldungen an die IT -----------------------------------------
  "Problem melden": "Report a problem",
  "Stimmt etwas in dieser Anwendung nicht? Die Meldung geht an die IT.":
    "Something wrong in this application? The report goes to IT.",
  "Stimmt in der App etwas nicht? Ab zur IT.": "Something off in the app? Straight to IT.",
  "Was stimmt nicht?": "What is wrong?",
  "z. B. Beleg lässt sich nicht speichern": "e.g. receipt will not save",
  "Was haben Sie gemacht?": "What were you doing?",
  "Welcher Schritt, was war erwartet, was kam stattdessen?":
    "Which step, what did you expect, what happened instead?",
  Bildschirmfoto: "Screenshot",
  "Mitgeschickt wird:": "Sent along:",
  "Meldung senden": "Send report",
  Art: "Kind",
  "Alle Arten": "All kinds",
  Support: "Support",

  // --- Wiederkehrende Schaltflaechen und Begriffe --------------------------
  Speichern: "Save",
  Abbrechen: "Cancel",
  Löschen: "Delete",
  Bearbeiten: "Edit",
  Anzeigen: "Show",
  Filtern: "Filter",
  Zurücksetzen: "Reset",
  Suche: "Search",
  Status: "Status",
  Alle: "All",
  Sprache: "Language",
  "Sprache wählen": "Choose language",

  // --- Die übrige Oberfläche -----------------------------------------------
  // Alphabetisch, damit sich ein Eintrag wiederfinden lässt.
  "– bitte wählen –": "- please choose -",
  "– der übliche Export aus dem Online-Banking (Sparkasse, DKB, ING, Comdirect, Volksbank, Qonto, N26). Spalten werden automatisch erkannt.": "- the usual export from online banking (Sparkasse, DKB, ING, Comdirect, Volksbank, Qonto, N26). Columns are detected automatically.",
  "– kein Konto zugeordnet –": "- no account assigned -",
  "– keine –": "- none -",
  "– keine Angabe –": "- not specified -",
  "– keine Zuordnung –": "- not assigned -",
  "– keins –": "- none -",
  "– klassisches SWIFT-Format (.sta).": "- classic SWIFT format (.sta).",
  "– XML-Auszug, enthält auch den Schlusssaldo.": "- XML statement, includes the closing balance.",
  "(Sie)": "(you)",
  "§ 19 BMG erfüllt": "Meets § 19 BMG",
  "✓ Abhaken": "✓ Tick off",
  "✓ Bezahlt": "✓ Paid",
  "1. Vertragsparteien": "1. Parties to the contract",
  "2. Mietgegenstand": "2. Rented property",
  "3. Mietzeit und Mietzins": "3. Term and rent",
  "4. Vertragsbedingungen": "4. Terms and conditions",
  "5. Hausordnung": "5. House rules",
  "6. Unterschrift": "6. Signature",
  "ab. Die Belege liegen bereits in den Monatsordnern daneben.": "The receipts are already filed next to it in the monthly folders.",
  "Abgehakt": "Ticked off",
  "Abgelegt": "Filed",
  "Abgelegtes PDF öffnen": "Open filed PDF",
  "Ablage": "Unassigned",
  "Ablegen": "File",
  "Adresse": "Address",
  "Adresse der Anwendung": "Application address",
  "Adresse und Ansprechpartner der Unterkunft. Zimmer und Betten legen Sie anschließend im Objekt an.": "Address and contact for the accommodation. You add rooms and beds inside the property afterwards.",
  "Aktion": "Action",
  "Aktiv": "Active",
  "Aktives Mietverhältnis": "Active tenancy",
  "Alle außer ehemaligen": "All except former",
  "Alle Bankumsätze mit Kategorie, Objekt, Mieter und Beleg-Link": "All bank transactions with category, property, tenant and receipt link",
  "Alle Belege mit Betrag, USt-Satz, Lieferant und Ablageort": "All receipts with amount, VAT rate, supplier and filing location",
  "Alle fälligen Mieten sind bezahlt.": "All rent due has been paid.",
  "Alle Objekte": "All properties",
  "Alle offenen Posten": "All open items",
  "Alle Umsätze aus den importierten Kontoauszügen.": "All transactions from the imported bank statements.",
  "Alle Unterkünfte mit Zimmern und Betten.": "All accommodation with rooms and beds.",
  "Alle Verträge sind unterschrieben.": "All contracts have been signed.",
  "Alle Zahlen und Belege eines Jahres – als CSV zum Herunterladen und als Exportordner für die Kanzlei.": "A year's figures and receipts - as CSV to download and as an export folder for your accountant.",
  "Alles optional, hilft aber im Alltag.": "All optional, but useful day to day.",
  "Alles zugeordnet": "Everything assigned",
  "Als ehemaligen Mieter anlegen": "Create as former tenant",
  "Als unterschrieben markieren": "Mark as signed",
  "an – das Konto wird dabei angelegt.": "- the account is created in the process.",
  "An diese Adresse geht der Vertragslink.": "The contract link goes to this address.",
  "Änderungen wirken nur auf neue Verträge – bereits freigegebene behalten ihren Wortlaut.": "Changes apply to new contracts only - those already issued keep their wording.",
  "Anfangssaldo": "Opening balance",
  "Angemietet – wir sind Zwischenmieter": "Rented - we are the intermediate tenant",
  "Anschrift": "Address",
  "Ansprechpartner und Hinweise": "Contact and notes",
  "Art des Vordrucks": "Kind of form",
  "Aufenthaltstitel": "Residence permit",
  "Auftraggeber / Entsendefirma": "Client / posting company",
  "ausführen.": "run.",
  "Ausgaben": "Expenses",
  "Ausgaben (Monat)": "Expenses (month)",
  "Ausgaben ohne Beleg": "Expenses without a receipt",
  "Ausgang": "Outgoing",
  "Auslastung": "Occupancy",
  "Auslastung je Objekt": "Occupancy per property",
  "Ausweis und Meldeanschrift": "ID and registered address",
  "Ausweis-/Passnummer": "ID / passport number",
  "Ausweisart": "Kind of ID",
  "Ausweisnummer": "ID number",
  "Auswertung": "Summary",
  "Auszug am": "Moved out on",
  "Auszug und alle daraus importierten Buchungen entfernen?": "Remove this statement and every transaction imported from it?",
  "Auszüge in Kürze": "Statements at a glance",
  "Bank": "Bank",
  "Bankdatei hochladen – die Buchungen werden eingelesen, Duplikate übersprungen und Mietzahlungen automatisch zugeordnet.": "Upload a bank file - transactions are read in, duplicates skipped and rent payments matched automatically.",
  "Bankkonten": "Bank accounts",
  "Bankkonto *": "Bank account *",
  "Bankkonto des Objekts": "Property bank account",
  "Bankkonto hinzufügen": "Add bank account",
  "Bankverbindung": "Bank details",
  "Basis-Adresse": "Base address",
  "Basis-Adresse:": "Base address:",
  "Beenden": "End",
  "Beendet": "Ended",
  "Bei angemieteten Objekten: unser Vermieter": "For rented properties: our landlord",
  "Beim Zuordnen entsteht aus dem Scan ein unterschriebener Mietvertrag, sofern der Mieter ein Mietverhältnis hat – der Vertrag erscheint dann unter Mietverträge. Ehemalige Mieter ohne Mietverhältnis bekommen den Scan zu ihren Unterlagen.": "Assigning turns the scan into a signed rental contract, provided the tenant has a tenancy - the contract then appears under Rental contracts. Former tenants without a tenancy get the scan added to their documents.",
  "Beleg": "Receipt",
  "Beleg *": "Receipt *",
  "Beleg erfassen": "Add receipt",
  "Beleg hochladen": "Upload receipt",
  "Beleg speichern": "Save receipt",
  "Belegdatum": "Receipt date",
  "Belegliste": "Receipt list",
  "Belegt": "Occupied",
  "Beraternummer": "Advisor number",
  "Betrag": "Amount",
  "Betrag (€)": "Amount (€)",
  "Betreuung": "Support",
  "Bett": "Bed",
  "Bett anlegen": "Add bed",
  "Bett gesperrt": "Bed blocked",
  "Bett hinzufügen": "Add bed",
  "Bett löschen": "Delete bed",
  "Bett zuweisen und Vertrag erzeugen": "Assign a bed and create the contract",
  "Betten": "Beds",
  "Betten anlegen": "Add beds",
  "Betten gesamt": "Beds in total",
  "Betten können direkt mit angelegt werden – das spart den zweiten Schritt.": "Beds can be added right away - that saves the second step.",
  "Bezahlt": "Paid",
  "Bezeichnung": "Name",
  "Bezeichnung *": "Name *",
  "Bis": "Until",
  "Bitte": "Please",
  "Datei": "File",
  "Datei *": "File *",
  "DATEV-Buchungsstapel": "DATEV posting batch",
  "DATEV-Stammdaten": "DATEV master data",
  "Datum": "Date",
  "davon aktiv": "of those active",
  "davon Nebenkosten": "of which utilities",
  "DE00 0000 0000 0000 0000 00": "DE00 0000 0000 0000 0000 00",
  "Deaktivieren": "Deactivate",
  "Deaktiviert": "Deactivated",
  "Der Link ist ungültig. Bitte wenden Sie sich an Ihre Hausverwaltung.": "This link is not valid. Please contact your property management.",
  "Der mitgelieferte Text ist eine praxisnahe Vorlage für die vorübergehende Überlassung von Schlafplätzen (§ 549 Abs. 2 Nr. 1 BGB), aber keine Rechtsberatung. Lassen Sie ihn einmalig anwaltlich prüfen und passen Sie ihn hier an.": "The text supplied is a practical template for the temporary provision of sleeping places (§ 549 (2) no. 1 BGB), but it is not legal advice. Have it reviewed by a lawyer once and adjust it here.",
  "Der Vertrag wird gerade vorbereitet. Bitte versuchen Sie es später erneut.": "The contract is being prepared. Please try again later.",
  "Der Vordruck nach § 19 BMG, mit dem sich Ihre Mieter beim Meldeamt anmelden.": "The form under § 19 BMG that your tenants use to register with the residents' office.",
  "Diese Angaben brauchen wir für den Vertrag und die Meldepflicht.": "We need these details for the contract and the registration requirement.",
  "Diese Angaben erscheinen im Kopf jedes Mietvertrags.": "These details appear at the top of every rental contract.",
  "Diese Eingänge konnten keiner Mietforderung zugeordnet werden.": "These incoming payments could not be matched to any rent charge.",
  "Diese Nummern vergibt Ihre Kanzlei. Ohne sie ist der Buchungsstapel trotzdem lesbar, DATEV fragt die Zuordnung dann beim Einlesen ab.": "Your accountant assigns these numbers. Without them the posting batch is still readable; DATEV will ask for the assignment when importing.",
  "Diese PDF enthält keine Formularfelder. Wohnwerk kann sie deshalb nicht ausfüllen – sie lässt sich nur als Blankovordruck ausdrucken. Felder lassen sich in Acrobat oder LibreOffice ergänzen.": "This PDF contains no form fields, so Wohnwerk cannot fill it in - it can only be printed blank. Fields can be added in Acrobat or LibreOffice.",
  "Dieser Link ist nicht mehr gültig. Bitte fordern Sie bei der Hausverwaltung einen neuen an.": "This link is no longer valid. Please ask your property management for a new one.",
  "Dieser Mietvertrag wurde storniert und kann nicht mehr unterschrieben werden.": "This rental contract has been cancelled and can no longer be signed.",
  "Dieses Objekt ist inaktiv": "This property is inactive",
  "Direkt herunterladen": "Download directly",
  "Dokument": "Document",
  "Dokumente": "Documents",
  "Dokumentenablage": "Document storage",
  "Dokumentenablage nicht erreichbar": "Document storage not reachable",
  "Download": "Download",
  "E-Mail *": "Email *",
  "E-Mail Betreuung": "Support email",
  "E-Mail des Steuerberaters": "Accountant's email",
  "E-Mail schreiben": "Write an email",
  "Ehemalige Mieter – Verträge beendet": "Former tenants - contracts ended",
  "Eigenes Passwort ändern": "Change your own password",
  "Eigentum von Wohnwerk": "Owned by Wohnwerk",
  "Eigentumsverhältnis": "Ownership",
  "Ein gescannter Vertrag landet hier und kann anschließend zugeordnet werden.": "A scanned contract lands here and can then be assigned.",
  "Ein Objekt ist eine Unterkunft mit Adresse. Darin legen Sie Zimmer und in den Zimmern die einzelnen Betten an.": "A property is one accommodation with an address. Inside it you add rooms, and inside the rooms the individual beds.",
  "Ein Steuerberater-Konto sieht Buchungen, Belege, Kontoauszüge und die Exporte. Ändern kann es nichts.": "An accountant account sees transactions, receipts, bank statements and the exports. It cannot change anything.",
  "Eine Klausel je Zeile.": "One clause per line.",
  "Eingang": "Incoming",
  "Eingang im Online-Banking gesehen – als bezahlt abhaken": "Seen in online banking - tick off as paid",
  "Eingang im Online-Banking gesehen – als bezahlt vermerken": "Seen in online banking - record as paid",
  "Eingänge auf diesem Konto werden beim Import automatisch dem Objekt zugeordnet.": "Payments into this account are assigned to the property automatically on import.",
  "Eingegangen": "Received",
  "Eingegangen am": "Received on",
  "Eingescannte Mietverträge, die noch keinem Mieter gehören. Namen sind in Verträgen und Listen nicht immer gleich geschrieben – hier wird von Hand zugeordnet.": "Scanned rental contracts that do not belong to a tenant yet. Names are not always spelled the same way in contracts and lists - assign them by hand here.",
  "Einleitung": "Introduction",
  "Einnahmen": "Income",
  "Einnahmen (Monat)": "Income (month)",
  "Einnahmen / Monat": "Income / month",
  "Einnahmen und Ausgaben": "Income and expenses",
  "Einrichten": "Set up",
  "Einstellungen → Benutzer": "Settings → Users",
  "Einstellungen speichern": "Save settings",
  "Einzelner Monat": "Single month",
  "Entfernen": "Remove",
  "Enthält die PDF Formularfelder, trägt Wohnwerk Name, Vorname und Einzugsdatum des Mieters automatisch ein. Sie prüfen die Zuordnung anschließend einmalig.": "If the PDF has form fields, Wohnwerk fills in the tenant's surname, first name and move-in date automatically. You check the mapping once afterwards.",
  "Entsendende Firma": "Posting company",
  "Entwurf": "Draft",
  "Entwürfe": "Drafts",
  "Erlassen": "Waived",
  "Erneut versenden": "Send again",
  "Erstes Objekt anlegen": "Add your first property",
  "Es erscheint nicht mehr im Belegungsplan, in der Bettauswahl für neue Mieter und in den Kennzahlen. Alle Buchungen, Verträge und Dokumente bleiben erhalten. Über „Wieder aktivieren“ kommt es jederzeit zurück.": "It no longer appears in the occupancy plan, in the bed picker for new tenants or in the figures. All transactions, contracts and documents are kept. \"Reactivate\" brings it back at any time.",
  "Es gibt noch kein Konto. Melden Sie sich mit den Werten aus": "There is no account yet. Sign in with the values from",
  "Etage": "Floor",
  "Export erzeugen und ablegen": "Create and file the export",
  "Export in die Ablage": "Export to storage",
  "Exportordner": "Export folder",
  "EXTF-Format für die Kanzlei – direkt in DATEV einlesbar": "EXTF format for your accountant - imports straight into DATEV",
  "Fällig": "Due",
  "Fällig am": "Due on",
  "Fälligkeit": "Due date",
  "Fehlende Belege anzeigen": "Show missing receipts",
  "fehlt": "missing",
  "Firma": "Company",
  "Firma / Name *": "Company / name *",
  "Firmen-PLZ": "Company postcode",
  "Firmenort": "Company town",
  "Firmenstraße": "Company street",
  "Forderung als erlassen markieren?": "Mark this charge as waived?",
  "Forderung erlassen": "Waive charge",
  "Forderungen angezeigt": "charges shown",
  "Forderungen entstehen automatisch für jedes laufende Mietverhältnis. Über „Forderungen erzeugen“ können Sie fehlende Monate nachholen.": "Charges are created automatically for every running tenancy. Use \"Create charges\" to catch up on missing months.",
  "Forderungen erzeugen": "Create charges",
  "Forderungen, deren Fälligkeit erreicht ist und die noch nicht ausgeglichen sind": "Charges that are due and not yet settled",
  "Format": "Format",
  "Frei": "Free",
  "Freigegeben und Link erzeugt": "Issued and link created",
  "Für den Steuerberater sollte zu jeder Ausgabe ein Beleg vorliegen.": "Your accountant should have a receipt for every expense.",
  "Für diesen Monat sind noch keine Mietforderungen erzeugt. Forderungen entstehen automatisch für jedes laufende Mietverhältnis.": "No rent charges have been created for this month yet. Charges are created automatically for every running tenancy.",
  "Für dieses Objekt sind noch keine Betten angelegt.": "No beds have been added for this property yet.",
  "Für Verträge, die auf Papier unterschrieben wurden. Es wird kein Unterschriftsbild hinterlegt.": "For contracts signed on paper. No signature image is stored.",
  "Gebucht": "Posted",
  "Geburtsdatum": "Date of birth",
  "Gegenpartei / Zweck": "Counterparty / purpose",
  "Gemeldete Probleme mit dieser Anwendung – liegen bei der IT.": "Reported problems with this application - with IT.",
  "Gemeldete Schäden und Anliegen aus den Objekten.": "Reported damage and issues from the properties.",
  "Genau dieser Text erscheint im PDF und beim Mieter.": "Exactly this text appears in the PDF and for the tenant.",
  "Geöffnet": "Opened",
  "Geschäftskonto": "Business account",
  "gesperrt": "blocked",
  "Gesperrt": "Blocked",
  "Größe (m²)": "Size (m²)",
  "Haken zurücknehmen": "Undo tick",
  "Handbestätigung zurücknehmen": "Undo manual confirmation",
  "Handelsregister": "Commercial register",
  "Hausmeister / Betreuung": "Caretaker / support",
  "Hausordnung": "House rules",
  "heute": "today",
  "Hier mit Maus oder Finger unterschreiben": "Sign here with mouse or finger",
  "Hilft beim Zuordnen, ist aber nicht zwingend.": "Helps with matching, but is not required.",
  "Hinweis": "Note",
  "Hinzufügen": "Add",
  "Hochladen und einlesen": "Upload and import",
  "Höchstens 12 MB. Lässt sich später jederzeit austauschen.": "12 MB at most. Can be swapped out any time later.",
  "https://verwaltung.beispiel.de": "https://management.example.com",
  "IBAN *": "IBAN *",
  "Ich habe den Mietvertrag und die Hausordnung gelesen und erkenne beide an. Mir ist bekannt, dass die elektronische Unterschrift der Textform nach § 126b BGB entspricht.": "I have read and accept the rental contract and the house rules. I understand that the electronic signature satisfies the text form under § 126b BGB.",
  "Ignorieren": "Ignore",
  "Ignoriert": "Ignored",
  "Ihr Mietvertrag": "Your rental contract",
  "Ihre Angaben vervollständigen": "Complete your details",
  "Importiert": "Imported",
  "Importierte Auszüge": "Imported statements",
  "In der Ablage": "Unassigned",
  "In der Ablage liegt kein Vertrag mehr. Neue Scans können Sie oben hochladen.": "No contracts left unassigned. You can upload new scans above.",
  "In diesem Zimmer ist noch kein Bett angelegt.": "No bed has been added to this room yet.",
  "Inaktiv": "Inactive",
  "Inaktiv stellen": "Set inactive",
  "Inhalt": "Content",
  "Jahr": "Year",
  "Jahr wechseln": "Change year",
  "jährlich": "yearly",
  "Je Monat": "Per month",
  "Jeder abgelegte Stand bleibt hier nachvollziehbar – wer der Kanzlei wann welche Zahlen übergeben hat.": "Every filed version stays traceable here - who handed which figures to the accountant, and when.",
  "Jeder Beleg wird beim Hochladen direkt in den richtigen Monatsordner gelegt. Die CSV-Dateien enthalten zu jeder Buchung den Link auf den passenden Beleg – der Steuerberater muss nichts suchen.": "Every receipt goes straight into the right monthly folder on upload. The CSV files carry a link to the matching receipt for each transaction - your accountant has nothing to search for.",
  "Jetzt zuordnen": "Assign now",
  "Kategorie": "Category",
  "Kategorie zuordnen oder als erledigt markieren.": "Assign a category or mark as done.",
  "Kaution": "Deposit",
  "Kein Dokument": "No document",
  "Kein Mietverhältnis": "No tenancy",
  "Kein offener Zahlungseingang vorhanden.": "No unmatched incoming payments.",
  "Kein Ordner-Freigeben nötig – der Steuerberater arbeitet direkt in der App.": "No folder sharing needed - your accountant works directly in the app.",
  "keine": "none",
  "Keine befristeten Mietverhältnisse.": "No fixed-term tenancies.",
  "Keine Belege": "No receipts",
  "Keine Betten vorhanden": "No beds",
  "keine Datei": "no file",
  "Keine Forderungen": "No charges",
  "Keine Objekte vorhanden": "No properties",
  "Keine Verträge": "No contracts",
  "Kontakt": "Contact",
  "Konto": "Account",
  "Konto anlegen": "Create account",
  "Konto Ausgaben": "Expense account",
  "Konto Mieteinnahmen": "Rental income account",
  "Kontoauszug": "Bank statement",
  "Kontoauszug hochladen": "Upload bank statement",
  "Kosten / Monat": "Costs / month",
  "Kosten fehlen": "Costs missing",
  "Kündigungsfrist": "Notice period",
  "Kürzel": "Short code",
  "Laden Sie einen Kontoauszug hoch, um Einnahmen und Ausgaben zu sehen.": "Upload a bank statement to see income and expenses.",
  "Laden Sie rechts einen Beleg hoch oder ordnen Sie ihn direkt bei einer Buchung zu.": "Upload a receipt on the right, or attach one directly to a transaction.",
  "Land": "Country",
  "Laufende Mieten": "Rent running",
  "Laufende Mietverhältnisse": "Running tenancies",
  "leer lassen": "leave empty",
  "Leer lassen für unbefristet.": "Leave empty for open-ended.",
  "Legen Sie Ihr erstes Objekt mit Zimmern und Betten an, um die Auslastung zu sehen.": "Add your first property with rooms and beds to see occupancy.",
  "Legen Sie unten das erste Zimmer an. Die Betten können Sie direkt mit erzeugen.": "Add the first room below. You can create the beds along with it.",
  "Legen Sie zuerst ein Objekt mit Zimmern und Betten an.": "Add a property with rooms and beds first.",
  "Legt das PDF in der Dokumentenablage unter „Mietverträge“ ab.": "Files the PDF in document storage under \"Rental contracts\".",
  "Legt den Namen als ehemaligen Mieter an und hängt den Vertrag dort ein": "Creates the name as a former tenant and attaches the contract there",
  "Legt die CSV-Dateien unter": "Files the CSV files under",
  "Letzte 12 Monate aus den importierten Kontoauszügen": "Last 12 months from the imported bank statements",
  "Letzte Anmeldung": "Last sign-in",
  "Lieferant": "Supplier",
  "Link abgelaufen": "Link expired",
  "Link für den Mieter": "Link for the tenant",
  "Mandantennummer": "Client number",
  "Meldeanschrift": "Registered address",
  "Meldeanschrift (Heimatadresse)": "Registered address (home address)",
  "Mietbeginn": "Start of tenancy",
  "Mietbeginn *": "Start of tenancy *",
  "Miete": "Rent",
  "Miete / Monat": "Rent / month",
  "Miete je Bett / Monat": "Rent per bed / month",
  "Miete monatlich": "Monthly rent",
  "Miete pro Monat": "Rent per month",
  "Mietende": "End of tenancy",
  "Mieter auswählen …": "Choose tenant …",
  "Mieter endgültig löschen": "Delete tenant permanently",
  "Mieter löschen": "Delete tenant",
  "Mieter ohne Mietvertrag": "Tenants without a contract",
  "Mieter zuordnen": "Assign tenant",
  "Mieter zur Auswahl": "tenants to choose from",
  "Mietverhältnis bearbeiten": "Edit tenancy",
  "Mietverhältnis beenden": "End tenancy",
  "Mietverhältnis löschen": "Delete tenancy",
  // --- Zimmerplan -----------------------------------------------------------
  "Zimmerplan": "Room plan",
  "{belegt} belegt · {frei} frei · {gesamt} Betten gesamt": "{belegt} occupied · {frei} free · {gesamt} beds in total",
  "Zimmer und Betten bearbeiten": "Edit rooms and beds",
  "noch nie zugewiesen": "never assigned",
  "heute aus {bett} genommen": "removed from {bett} today",
  "bis {datum} in {bett}": "until {datum} in {bett}",
  "Ohne Stockwerk": "No floor",
  "Ohne Bett": "No bed",
  "Das hat nicht geklappt. Bitte Seite neu laden und noch einmal versuchen.": "That did not work. Please reload the page and try again.",
  "{a} und {b} tauschen die Betten?": "{a} and {b} swap beds?",
  "{name} aus dem Zimmer nehmen? Das Mietverhältnis endet heute; wird die Person heute noch auf ein anderes Bett gesetzt, läuft es weiter.":
    "Remove {name} from the room? The tenancy ends today; if the person is put on another bed today, it continues.",
  "Ausgewählt – jetzt Ziel antippen": "Selected. Now tap the destination",
  "Ziehen oder antippen, dann Ziel wählen": "Drag, or tap and then choose the destination",
  "{name} ausgewählt – ein Bett antippen zum Verschieben, „Ohne Bett“ zum Herausnehmen. Esc bricht ab.":
    "{name} selected. Tap a bed to move, or \"No bed\" to remove. Esc cancels.",
  "Dieses Objekt hat noch keine Zimmer. Zimmer und Betten legen Sie auf der Objektseite an.": "This property has no rooms yet. Create rooms and beds on the property page.",
  "Stockwerk fehlt – auf der Objektseite beim Zimmer unter „Etage“ eintragen, dann sortiert sich der Plan.":
    "Floor missing. Enter it under \"Floor\" on the room on the property page and the plan sorts itself.",
  "{name} aus dem Zimmer nehmen": "Remove {name} from the room",
  "Aus dem Zimmer nehmen": "Remove from the room",
  "frei": "free",
  "Keine Betten in diesem Zimmer.": "No beds in this room.",
  "Personen ohne Bett – über alle Objekte. Auf ein freies Bett ziehen, um sie in {objekt} einzuquartieren; jemanden hierher ziehen, um ihn aus dem Zimmer zu nehmen.":
    "People without a bed, across all properties. Drag onto a free bed to house them in {objekt}; drag someone here to remove them from the room.",
  "Alle haben ein Bett.": "Everyone has a bed.",
  "{n} belegt": "{n} occupied",
  "{n} frei": "{n} free",
  "{n} gesamt": "{n} total",
  "ab {datum}": "from {datum}",
  "{name} und {anderer} haben getauscht: {a} ⇄ {b}.": "{name} and {anderer} swapped: {a} ⇄ {b}.",
  "{name} umgezogen: {a} → {b}. Vertrag und Forderungen bleiben.": "{name} moved: {a} → {b}. Contract and charges stay.",
  "{bett} ist belegt. Zum Tauschen die Person mit Bett auf das andere Bett ziehen.": "{bett} is occupied. To swap, drag the person who has a bed onto the other bed.",
  "{name} wieder eingesetzt: {bett}. Das Mietverhältnis läuft weiter.": "{name} put back: {bett}. The tenancy continues.",
  "{name} auf {bett} gesetzt – Vertragsentwurf ab heute mit {miete} und 200,00 € Kaution. Anpassen auf der Mieterseite.":
    "{name} placed on {bett}. Contract draft from today with {miete} and a €200.00 deposit. Adjust on the tenant page.",
  "{name} aus {bett} genommen – der Vertragsentwurf wurde gelöscht.": "{name} removed from {bett}. The contract draft was deleted.",
  "{name} aus {bett} genommen – Mietverhältnis endet heute. Bis heute Abend wieder einsetzen, und es läuft weiter.":
    "{name} removed from {bett}. The tenancy ends today. Put them back by tonight and it continues.",
  "Mietverhältnis wurde zum {datum} beendet. Das Bett ist ab dann wieder frei.": "Tenancy ended on {datum}. The bed is free again from then on.",
  "Letzter Monat auf {tage} Tage gekürzt: {nachher} statt {vorher}.": "Last month reduced to {tage} days: {nachher} instead of {vorher}.",
  "Der letzte Monat ist schon voll bezahlt – {betrag} zu viel, bitte mit der Kaution verrechnen.": "The last month is already paid in full: {betrag} too much, please offset it against the deposit.",
  "{anzahl} offene Forderung(en) nach dem Auszug entfernt.": "{anzahl} open charge(s) after the move-out removed.",
  "{anzahl} offene Forderung(en) neu berechnet.": "{anzahl} open charge(s) recalculated.",
  "{anzahl} offene Forderung(en) außerhalb des Zeitraums entfernt.": "{anzahl} open charge(s) outside the period removed.",
  "Bett wechseln": "Change bed",
  "Umzug in ein anderes Bett, auch in eine andere Wohnung. Beginn, Miete, Kaution, Vertrag und Forderungen bleiben unverändert.":
    "Move to another bed, even in another flat. Start date, rent, deposit, contract and charges stay unchanged.",
  "Umziehen": "Move",
  "Bitte ein Bett wählen.": "Please choose a bed.",
  "Das ist bereits das aktuelle Bett.": "That is already the current bed.",
  "Bett nicht gefunden.": "Bed not found.",
  "Dieses Bett ist gesperrt.": "This bed is blocked.",
  "Das Bett ist im Zeitraum bereits belegt: {name}.": "The bed is already taken in that period: {name}.",
  "Umgezogen: {vorher} → {nachher}. Vertrag und Forderungen bleiben unverändert.":
    "Moved: {vorher} → {nachher}. Contract and charges stay unchanged.",
  "Für Versehen: falsches Bett oder falsche Person. Vertragsentwurf und offene Forderungen werden mit entfernt, das Bett ist danach wieder frei.":
    "For mistakes: wrong bed or wrong person. The contract draft and open charges are removed with it, and the bed is free again afterwards.",
  "Mietverhältnis {bett} wirklich löschen? Vertragsentwurf und Forderungen gehen mit.":
    "Really delete the tenancy {bett}? The contract draft and charges go with it.",
  "Der Vertrag ist unterschrieben – ein solches Mietverhältnis wird beendet, nicht gelöscht.":
    "The contract is signed. A tenancy like this is ended, not deleted.",
  "Zu diesem Mietverhältnis sind schon Zahlungen verbucht – bitte beenden statt löschen.":
    "Payments have already been recorded for this tenancy. Please end it instead of deleting it.",
  "Mietverhältnis gelöscht. Das Bett {bett} ist wieder frei.": "Tenancy deleted. Bed {bett} is free again.",
  "Mietverhältnis wirklich beenden? Das Bett wird danach wieder als frei geführt.": "Really end this tenancy? The bed will be listed as free again.",
  "Mietverhältnisse": "Tenancies",
  "Mietverhältnisse mit festem Ende": "Tenancies with a fixed end",
  "Mietvertrag": "Rental contract",
  "Mietvertrag fehlt": "Rental contract missing",
  "Mietvertrag mit Wohnungsgeberbestätigung": "Rental contract with landlord confirmation",
  "Mietvertrag und Wohnungsgeberbestätigung als PDF. Wohnwerk füllt nur die Formularfelder aus – am Layout ändert sich nichts.": "Rental contract and landlord confirmation as a PDF. Wohnwerk only fills in the form fields - the layout stays untouched.",
  "Mit der Kanzlei abstimmen": "Agree with your accountant",
  "Möblierter Schlafplatz zum vorübergehenden Gebrauch (Monteurunterkunft)": "Furnished sleeping place for temporary use (contractor accommodation)",
  "Monat": "Month",
  "Monat für Monat abhaken, welche Mieten schon da sind – von Hand oder automatisch per Kontoauszug.": "Tick off month by month which rent has arrived - by hand or automatically from a bank statement.",
  "monatlich": "monthly",
  "Monatliche Mietforderungen und ihre Zahlungseingänge.": "Monthly rent charges and the payments received against them.",
  "Monteure und Mitarbeiter mit ihren Mietverhältnissen.": "Contractors and staff with their tenancies.",
  "Monteurhaus Hafenstraße": "Monteurhaus Hafenstraße",
  "MT940": "MT940",
  "Nach dem ersten Import sehen Sie hier alle Läufe mit Zeitraum und Trefferzahl.": "After the first import you will see every run here, with its period and number of matches.",
  "Nachname": "Surname",
  "Nachname *": "Surname *",
  "Name": "Name",
  "Name der unterschreibenden Person": "Name of the person signing",
  "Name im Vertrag": "Name in the contract",
  "Name, E-Mail oder Firma": "Name, email or company",
  "Neuen Link erzeugen": "Create a new link",
  "Neuen Link erzeugen? Der bisherige Link wird sofort ungültig.": "Create a new link? The previous one stops working immediately.",
  "Neuer Mieter": "New tenant",
  "Neuer Mieter mit Vertrag": "New tenant with contract",
  "Neues Objekt": "New property",
  "Neues Passwort": "New password",
  "nicht hinterlegt": "not stored",
  "Nicht zugeordnete Eingänge": "Unmatched incoming payments",
  "Nicht zugeordnete Zahlungseingänge": "Unmatched incoming payments",
  "nicht zugewiesen": "not assigned",
  "Noch kein Auszug importiert": "No statement imported yet",
  "Noch kein Bett zugewiesen. Weisen Sie unten eines zu, um den Vertrag zu erzeugen.": "No bed assigned yet. Assign one below to create the contract.",
  "Noch kein Export abgelegt. „Export erzeugen und ablegen“ erzeugt alle Dateien – einschließlich DATEV – und verzeichnet sie hier.": "No export filed yet. \"Create and file the export\" produces every file - DATEV included - and lists them here.",
  "Noch kein Konto hinterlegt.": "No account stored yet.",
  "Noch kein Objekt angelegt": "No property added yet",
  "Noch keine Buchungen": "No transactions yet",
  "Noch keine Objekte angelegt": "No properties added yet",
  "Noch keine Zimmer": "No rooms yet",
  "Noch nicht freigegeben": "Not issued yet",
  "Noch offen": "Still open",
  "Notiz": "Note",
  "npm run db:migrate": "npm run db:migrate",
  "Nur bezahlte": "Paid only",
  "Nur ehemalige Mieter": "Former tenants only",
  "Nur möglich, wenn kein laufendes Mietverhältnis besteht.": "Only possible when there is no running tenancy.",
  "Nur möglich, wenn keine laufenden Mietverhältnisse bestehen.": "Only possible when there are no running tenancies.",
  "Nur offene und Teilzahlungen": "Open and part-paid only",
  "Nur Wohnungsgeberbestätigung": "Landlord confirmation only",
  "Objekt": "Property",
  "Objekt anlegen": "Add property",
  "Objekt endgültig löschen": "Delete property permanently",
  "Objekt löschen": "Delete property",
  "Objekt öffnen": "Open property",
  "Objektdaten bearbeiten": "Edit property details",
  "Objektdaten speichern": "Save property details",
  "Offener Betrag": "Outstanding amount",
  "Öffnen": "Open",
  "Öffnet sich in Excel und LibreOffice ohne Umwege.": "Opens in Excel and LibreOffice without detours.",
  "Ohne Beleg": "No receipt",
  "Ohne Schrägstrich am Ende. Nach dem Verbinden der Domain in Vercel hier eintragen.": "No trailing slash. Enter it here after connecting the domain in Vercel.",
  "Ohne sie kann sich ein Mieter nicht anmelden. Der Vordruck unterscheidet sich je Kommune, deshalb gehört hier die Datei des zuständigen Meldeamts hinterlegt.": "Without it a tenant cannot register. The form differs from one municipality to the next, so the file from the responsible residents' office belongs here.",
  "Optional – wichtig, wenn die Firma die Miete zahlt.": "Optional - important when the company pays the rent.",
  "Optional, taucht in Auswertungen und Ordnernamen auf.": "Optional; appears in reports and folder names.",
  "Ordner freigeben": "Share folder",
  "Ordner in Google Drive öffnen": "Open folder in Google Drive",
  "Ort": "Town",
  "Ort *": "Town *",
  "Passwort ändern": "Change password",
  "PDF ansehen": "View PDF",
  "PDF neu erzeugen und ablegen": "Recreate and file the PDF",
  "PDF öffnen": "Open PDF",
  "PDF-Datei": "PDF file",
  "Per E-Mail-Programm senden": "Send via email program",
  "Person": "Person",
  "Person erfassen, Bett zuweisen – anschließend wird der Vertragsentwurf erzeugt.": "Record the person, assign a bed - the draft contract is created afterwards.",
  "Personalausweis": "Identity card",
  "Pflichtfelder sind mit * gekennzeichnet.": "Required fields are marked with *.",
  "PLZ *": "Postcode *",
  "Posten": "Item",
  "prüfen und": "check and",
  "Rechnung": "Invoice",
  "Rechnung Stadtwerke März": "Utilities invoice March",
  "Rechnungen und Quittungen – sicher abgelegt, sortiert nach Jahr und Monat.": "Invoices and receipts - safely filed, sorted by year and month.",
  "Rechtlicher Hinweis": "Legal notice",
  "Rechts können Sie das Geschäftskonto mit IBAN hinterlegen. Danach lassen sich Auszüge hochladen.": "You can store the business account with its IBAN on the right. After that you can upload statements.",
  "Reisepass": "Passport",
  "Richtung": "Direction",
  "Rolle": "Role",
  "Rückgängig": "Undo",
  "Sachkonto Bank": "Bank ledger account",
  "Saldo (Monat)": "Balance (month)",
  "Saldo laufender Monat": "Balance this month",
  "Sammelkonto, Kanzlei bucht um": "Holding account, your accountant reposts it",
  "Scan": "Scan",
  "Schlafplatz": "Sleeping place",
  "Schlusssaldo": "Closing balance",
  "SKR03: 1200": "SKR03: 1200",
  "So ist die Ablage aufgebaut": "How the storage is organised",
  "Sobald Sie einem Mieter ein Bett zuweisen, entsteht automatisch ein Vertragsentwurf.": "As soon as you assign a bed to a tenant, a draft contract is created automatically.",
  "Soll": "Due",
  "Soll gesamt": "Total due",
  "Soll und Ist je Mieter und Monat, inklusive offener Posten": "Due and received per tenant and month, including open items",
  "Sonst": "Otherwise",
  "Sonstiges": "Other",
  "Staatsangehörigkeit": "Nationality",
  "Stammdaten": "Master data",
  "Stammdaten bearbeiten": "Edit master data",
  "Stammdaten speichern": "Save master data",
  "Standardmiete je Bett": "Standard rent per bed",
  "Steht im Vertrag als Zahlungsziel für die Miete.": "Appears in the contract as the account for the rent.",
  "Steuerberater – nur Buchhaltung, nur lesend": "Accountant - accounting only, read-only",
  "Steuerberater-Export": "Accountant export",
  "Storniert": "Cancelled",
  "Straße": "Street",
  "Straße (Meldeanschrift)": "Street (registered address)",
  "Straße und Hausnummer": "Street and number",
  "Straße und Hausnummer *": "Street and number *",
  "Systemstatus": "System status",
  "Teilzahlung": "Part payment",
  "Telefon": "Phone",
  "Telefon Betreuung": "Support phone",
  "Titel": "Title",
  "Titel, Lieferant": "Title, supplier",
  "Turnus": "Interval",
  "Überfällig": "Overdue",
  "Überfällige Mieten": "Overdue rent",
  "Überschuss / Monat": "Surplus / month",
  "unbefristet": "open-ended",
  "Unsere Kosten": "Our costs",
  "Unterkunft": "Accommodation",
  "Unterkunft und Mietverhältnis": "Accommodation and tenancy",
  "Unterschrieben": "Signed",
  "Unterschrieben von": "Signed by",
  "Unterschrift": "Signature",
  "Unterschrift des Mieters": "Tenant's signature",
  "Unterschriftenfeld": "Signature pad",
  "Unterstützte Formate": "Supported formats",
  "Unterwegs abfotografieren – das Foto wird automatisch auf eine sinnvolle Größe gebracht.": "Photograph it on the go - the photo is resized to something sensible automatically.",
  "USt-IdNr.": "VAT ID",
  "USt-Satz %": "VAT rate %",
  "Vermietbar": "Lettable",
  "Vermieter": "Landlord",
  "Vermieter / Eigentümer": "Landlord / owner",
  "Vermieterdaten, Vertragstext, Ablage und Zugänge.": "Landlord details, contract text, storage and accounts.",
  "Versendet": "Sent",
  "Versendet, aber noch nicht unterschrieben": "Sent, but not signed yet",
  "Vertrag": "Contract",
  "Vertrag als PDF herunterladen": "Download contract as PDF",
  "Vertrag anlegen": "Create contract",
  "Vertrag beenden": "End contract",
  "Vertrag fehlt": "Contract missing",
  "Vertrag freigeben und versenden": "Issue and send the contract",
  "Vertrag hinterlegt": "Contract on file",
  "Vertrag nicht gefunden": "Contract not found",
  "Vertrag öffnen": "Open contract",
  "Vertrag rechtsverbindlich unterschreiben": "Sign the contract with legal effect",
  "Vertrag stornieren": "Cancel contract",
  "Vertrag stornieren? Das Bett wird wieder als frei geführt.": "Cancel the contract? The bed will be listed as free again.",
  "Vertrag storniert": "Contract cancelled",
  "Vertrag unterschrieben": "Contract signed",
  "Vertrag versendet": "Contract sent",
  "Verträge in Bearbeitung": "Contracts in progress",
  "Vertragsablage": "Unassigned contracts",
  "Vertragsbedingungen": "Terms and conditions",
  "Vertragsdatum": "Contract date",
  "Vertragsentwurf für dieses Mietverhältnis anlegen": "Create a draft contract for this tenancy",
  "Vertragsinhalt": "Contract content",
  "Vertragslinks": "Contract links",
  "Vertragstext": "Contract text",
  "Verwaltung – voller Zugriff": "Management - full access",
  "Verwaltung von Monteurunterkünften: Objekte, Zimmer und Betten, digitale Mietverträge und Buchhaltung.": "Management of contractor accommodation: properties, rooms and beds, digital rental contracts and accounting.",
  "Verwendungszweck": "Payment reference",
  "Vielen Dank. Ihr Mietvertrag ist gültig abgeschlossen – Sie können ihn hier jederzeit als PDF herunterladen.": "Thank you. Your rental contract is validly concluded - you can download it as a PDF here at any time.",
  "Vollständiger Name": "Full name",
  "Vom Entwurf über den Versand bis zur Unterschrift.": "From draft through sending to signature.",
  "Vom Mieter geöffnet": "Opened by the tenant",
  "Von": "From",
  "von Hand abgehakt": "ticked off by hand",
  "Vor der Übergabe prüfen": "Check before handing over",
  "Vor Ort unterschrieben erfassen": "Record as signed in person",
  "Vordruck hochladen": "Upload form",
  "Vordrucke": "Forms",
  "vorhanden": "on file",
  "Vorname": "First name",
  "Vorname *": "First name *",
  "Vorschau des aufgenommenen Belegs": "Preview of the captured receipt",
  "Vorschlag:": "Suggestion:",
  "Was das Objekt uns monatlich kostet – Miete an den Vermieter, Nebenkosten, Strom, Öl. Bei all-inclusive reicht ein Posten.": "What the property costs us each month - rent to the landlord, utilities, electricity, oil. For all-inclusive one item is enough.",
  "Weitere Schritte": "Next steps",
  "Weiteren Vertrag ablegen": "File another contract",
  "Weiteren Zugang anlegen": "Create another account",
  "Weiteres Bett zuweisen": "Assign another bed",
  "Welcher Wert gehört in welches Feld? Wohnwerk hat vorbelegt, was es aus den Feldnamen ableiten konnte.": "Which value belongs in which field? Wohnwerk has pre-filled what it could infer from the field names.",
  "Wer sich am Dashboard anmelden darf.": "Who may sign in to the dashboard.",
  "Wieder aktivieren": "Reactivate",
  "Wird aus dem Bett vorbelegt.": "Pre-filled from the bed.",
  "Wird beim Abgleich der Kontoauszüge auch als Zahlender erkannt.": "Also recognised as the payer when matching bank statements.",
  "Wird für die Vertragslinks an die Mieter verwendet.": "Used for the contract links sent to tenants.",
  "WLAN-Name": "Wi-Fi name",
  "WLAN-Passwort": "Wi-Fi password",
  "Wohnsitz des Mieters, nicht die Unterkunft.": "The tenant's home address, not the accommodation.",
  "Wohnungsgeberbestätigung": "Landlord confirmation",
  "Wohnungsgeberbestätigung fehlt": "Landlord confirmation missing",
  "Woran die Anwendung gerade angebunden ist.": "What the application is currently connected to.",
  "z. B. 12345": "e.g. 12345",
  "z. B. 678": "e.g. 678",
  "z. B. Arben Krasniqi": "e.g. Arben Krasniqi",
  "z. B. Miete an Vermieter, Strom, Öl": "e.g. rent to landlord, electricity, oil",
  "Zahler": "Payer",
  "Zahlung auf": "Payment to",
  "Zahlung zuordnen": "Match payment",
  "Zahlungen automatisch zuordnen": "Match payments automatically",
  "Zahlungseingang": "Incoming payment",
  "Zeigt Ausgaben ohne Beleg.": "Shows expenses without a receipt.",
  "Zeitraum": "Period",
  "Zimmer": "Room",
  "Zimmer / Bett": "Room / bed",
  "Zimmer 1": "Room 1",
  "Zimmer anlegen": "Add room",
  "Zimmer bearbeiten": "Edit room",
  "Zimmer hinzufügen": "Add room",
  "Zimmer löschen": "Delete room",
  "Zimmer speichern": "Save room",
  "Zimmer und Betten": "Rooms and beds",
  "Zu Buchung": "To transaction",
  "Zu den Einstellungen": "To settings",
  "Zu den Kontoauszügen": "To bank statements",
  "Zu den Mietverträgen": "To rental contracts",
  "Zuerst ein Bankkonto anlegen": "Add a bank account first",
  "Zugang anlegen": "Create account",
  "Zugang für den Steuerberater": "Account for your accountant",
  "Zugänge": "Accounts",
  "Zugeordnet": "Matched",
  "zum {tag}. eines Monats im Voraus": "on the {tag}th of each month in advance",
  "Zum aktuellen Monat": "To the current month",
  "Zum Mieter": "To tenant",
  "Zuordnen": "Assign",
  "Zuordnung aufheben": "Unassign",
  "Zuordnung speichern": "Save mapping",
  "Zweck, Name, Kategorie": "Purpose, name, category",

  // --- Rückmeldungen der Aktionen und Sätze mit eingesetzten Werten -------
  "– der gedruckte Kontoauszug (VR-Bank, Sparkasse und verwandte Layouts). Buchungen werden aus dem Text gelesen; gescannte Bilder ohne Textebene funktionieren nicht. CSV oder CAMT bleiben die verlässlichere Wahl, wo das Online-Banking sie anbietet.": "- the printed bank statement (VR-Bank, Sparkasse and similar layouts). Transactions are read from the text; scanned images without a text layer will not work. CSV or CAMT remain the more reliable choice wherever online banking offers them.",
  "„{name}“ inaktiv stellen? Es verschwindet aus Belegungsplan, Bettauswahl und Kennzahlen – Buchhaltung und Historie bleiben erhalten.": "Set \"{name}\" inactive? It disappears from the occupancy plan, the bed picker and the figures - accounting and history are kept.",
  "„{name}“ wirklich löschen?": "Really delete \"{name}\"?",
  "„{name}“ wurde angelegt.": "\"{name}\" has been created.",
  "({guete} % Namensähnlichkeit) – bitte prüfen.": "({guete}% name similarity) - please check.",
  "{adresse} · {zimmer} Zimmer, {betten} Betten": "{adresse} · {zimmer} rooms, {betten} beds",
  "{aktiv} aktive und {frueher} frühere Mietverhältnisse ohne hinterlegten Vertrag. Liegt der Vertrag als Scan vor, ordnen Sie ihn in der Ablage zu.": "{aktiv} active and {frueher} former tenancies with no contract on file. If you have the contract as a scan, assign it from the unassigned list.",
  "{anzahl} Ausgabe(n) ohne Beleg": "{anzahl} expense(s) without a receipt",
  "{anzahl} Bett(en), {belegt} belegt": "{anzahl} bed(s), {belegt} occupied",
  "{anzahl} Buchung(en)": "{anzahl} transaction(s)",
  "{anzahl} Buchung(en) dem Objekt des Kontos zugewiesen": "{anzahl} transaction(s) assigned to the account's property",
  "{anzahl} Buchung(en) importiert": "{anzahl} transaction(s) imported",
  "{anzahl} Buchung(en) noch nicht geprüft": "{anzahl} transaction(s) not yet reviewed",
  "{anzahl} Datei(en) wurden in {ablage} abgelegt.": "{anzahl} file(s) were filed in {ablage}.",
  "{anzahl} Duplikat(e) übersprungen": "{anzahl} duplicate(s) skipped",
  "{anzahl} Forderung(en), davon {ueberfaellig} überfällig": "{anzahl} charge(s), {ueberfaellig} of them overdue",
  "{anzahl} Hinweis(e) beim Einlesen": "{anzahl} note(s) while importing",
  "{anzahl} offene(s) Support-Ticket(s)": "{anzahl} open support ticket(s)",
  "{anzahl} offene(s) Ticket(s)": "{anzahl} open ticket(s)",
  "{anzahl} Vertrag/Verträge warten auf Zuordnung": "{anzahl} contract(s) waiting to be assigned",
  "{anzahl} Zahlung(en) automatisch zugeordnet": "{anzahl} payment(s) matched automatically",
  "{belegt} von {gesamt} vermietbaren Betten": "{belegt} of {gesamt} lettable beds",
  "{betrag} / Monat": "{betrag} / month",
  "{betrag} / Monat · Verwendungszweck": "{betrag} / month · payment reference",
  "{betrag} bei Vollbelegung": "{betrag} at full occupancy",
  "{betrag} im Jahr": "{betrag} per year",
  "{bezahlt} von {gesamt}": "{bezahlt} of {gesamt}",
  "{bezahlt} von {gesamt} abgehakt": "{bezahlt} of {gesamt} ticked off",
  "{datei} · {seiten} Seiten · {kb} KB · {felder} Formularfelder": "{datei} · {seiten} pages · {kb} KB · {felder} form fields",
  "{ein} ein · {aus} aus": "{ein} in · {aus} out",
  "{frei} von {gesamt} Betten sind derzeit frei. Ohne Bettauswahl wird nur der Mieter angelegt.": "{frei} of {gesamt} beds are free right now. Without picking a bed, only the tenant is created.",
  "{gezeigt} von {gesamt} Buchungen angezeigt. Bitte die Filter verwenden, um die Auswahl einzugrenzen.": "Showing {gezeigt} of {gesamt} transactions. Please use the filters to narrow the selection.",
  "{mit} von {gesamt}": "{mit} of {gesamt}",
  "{name} gilt als ehemaliger Mieter.": "{name} now counts as a former tenant.",
  "{name} ist wieder aktiv.": "{name} is active again.",
  "{name} wirklich löschen? Verträge und Mietkonto werden mitgelöscht.": "Really delete {name}? Contracts and the rent account go with them.",
  "{name} wurde als ehemaliger Mieter angelegt.": "{name} has been created as a former tenant.",
  "0,00 = keine Kaution; eine offene Kautionsforderung wird dann entfernt": "0.00 = no deposit; an open deposit charge is then removed",
  "0,00 eintragen = keine Kaution": "Enter 0.00 for no deposit",
  "Ablage nicht eingerichtet": "Storage not set up",
  "Ablage nicht erreichbar": "Storage not reachable",
  "Alle fälligen Mieten sind ausgeglichen.": "All rent due has been settled.",
  "alle vollständig": "all complete",
  "alles zugeordnet": "everything assigned",
  "Als bezahlt vermerkt.": "Recorded as paid.",
  "Bankkonto „{name}“ wurde angelegt.": "Bank account \"{name}\" has been created.",
  "Bankkonto nicht gefunden.": "Bank account not found.",
  "Bankkonto wurde gelöscht.": "Bank account has been deleted.",
  "Beleg „{titel}“ löschen?": "Delete receipt \"{titel}\"?",
  "Beleg nicht gefunden.": "Receipt not found.",
  "Beleg wurde gelöscht (in Drive in den Papierkorb verschoben).": "Receipt has been deleted (moved to the bin in Drive).",
  "Beleg wurde gespeichert.": "Receipt has been saved.",
  "Bereits als bezahlt vermerkt.": "Already recorded as paid.",
  "Bett {buchstabe}": "Bed {buchstabe}",
  "Bett wurde gelöscht.": "Bed has been deleted.",
  "Bett wurde gespeichert.": "Bed has been saved.",
  "Bezeichnung und ein Betrag über 0 sind nötig.": "A name and an amount above 0 are required.",
  "Bezeichnung und IBAN werden benötigt.": "Name and IBAN are required.",
  "Bitte beschreiben Sie das Anliegen in einem Satz.": "Please describe the issue in one sentence.",
  "Bitte beschreiben Sie in einem Satz, was nicht stimmt.": "Please describe in one sentence what is wrong.",
  "Bitte bestätigen Sie, dass Sie den Vertrag gelesen haben.": "Please confirm that you have read the contract.",
  "Bitte Bett und Mietbeginn auswählen.": "Please choose a bed and a start date.",
  "Bitte den Namen der unterschreibenden Person angeben.": "Please give the name of the person signing.",
  "Bitte ein Bankkonto auswählen.": "Please choose a bank account.",
  "Bitte eine Datei auswählen.": "Please choose a file.",
  "Bitte eine gültige E-Mail-Adresse angeben.": "Please give a valid email address.",
  "Bitte eine PDF-Datei auswählen.": "Please choose a PDF file.",
  "Bitte etwas schreiben.": "Please write something.",
  "Bitte prüfen Sie Ihre Angaben, ergänzen Sie fehlende Felder und unterschreiben Sie den Vertrag unten. Mietbeginn ist der {datum}.": "Please check your details, fill in anything missing and sign the contract below. The tenancy starts on {datum}.",
  "Bitte tragen Sie Ihren vollständigen Namen ein.": "Please enter your full name.",
  "Bitte unterschreiben Sie im dafür vorgesehenen Feld.": "Please sign in the field provided.",
  "Bitte zuerst einen Mieter auswählen.": "Please choose a tenant first.",
  "Buchung {datum} · {betrag}": "Transaction {datum} · {betrag}",
  "Buchung wurde gespeichert.": "Transaction has been saved.",
  "Danke – Meldung #{nummer} liegt bei der IT.": "Thank you - report #{nummer} is with IT.",
  "Das Bett ist belegt und kann nicht gelöscht werden.": "The bed is occupied and cannot be deleted.",
  "Das eigene Konto kann nicht deaktiviert werden.": "You cannot deactivate your own account.",
  "Das Konto hat {anzahl} Buchungen und kann nicht gelöscht werden.": "The account has {anzahl} transactions and cannot be deleted.",
  "Das Mietende darf nicht vor dem Mietbeginn liegen.": "The end of the tenancy cannot be before its start.",
  "Das Passwort muss mindestens 10 Zeichen haben.": "The password must be at least 10 characters.",
  "Das Zimmer braucht eine Bezeichnung.": "The room needs a name.",
  "Datei wählen": "Choose file",
  "DATEV-Einstellungen gespeichert.": "DATEV settings saved.",
  "Der Link ist abgelaufen – bitte einen neuen erzeugen.": "The link has expired - please create a new one.",
  "Der Link ist abgelaufen. Bitte fordern Sie einen neuen an.": "The link has expired. Please ask for a new one.",
  "Der Link wird erst nach der Freigabe gültig.": "The link only becomes valid once the contract is issued.",
  "Der Mieter hat ein laufendes Mietverhältnis. Bitte dieses zuerst beenden.": "The tenant has a running tenancy. Please end it first.",
  "Der Steuerberater erhält Leserechte auf den kompletten Jahresordner {jahr}.": "Your accountant gets read access to the whole {jahr} folder.",
  "Der Vertrag ist bereits unterschrieben.": "The contract has already been signed.",
  "Der Vertrag wurde nicht gefunden.": "The contract was not found.",
  "Der Vordruck muss eine PDF-Datei sein.": "The form must be a PDF file.",
  "Die Datei ist größer als 12 MB.": "The file is larger than 12 MB.",
  "Die Datei ist größer als 20 MB.": "The file is larger than 20 MB.",
  "Die Datei konnte nicht als PDF gelesen werden.": "The file could not be read as a PDF.",
  "Die IBAN sieht nicht gültig aus.": "That IBAN does not look valid.",
  "Diese E-Mail-Adresse wird bereits verwendet.": "That email address is already in use.",
  "Dieser Forderung sind Kontobewegungen zugeordnet – bitte dort lösen.": "This charge has bank transactions matched to it - please unmatch them there.",
  "Dieser Vertrag wurde storniert.": "This contract has been cancelled.",
  "Dokument nicht gefunden.": "Document not found.",
  "Dokumente werden normalerweise ohne jede Einrichtung direkt in der Supabase-Datenbank gespeichert. Erscheint diese Meldung, ist die Datenbank gerade nicht erreichbar – bitte in ein paar Minuten erneut versuchen. Uploads werden bis dahin nicht angenommen; Kontoauszüge werden trotzdem eingelesen, nur das Original wird nicht archiviert.": "Documents are normally stored straight in the Supabase database with no setup at all. If you see this message, the database is not reachable right now - please try again in a few minutes. Uploads are refused until then; bank statements are still imported, only the original is not archived.",
  "Ein neuer Link wurde erzeugt. Der alte ist ungültig.": "A new link has been created. The old one is no longer valid.",
  "Ein unterschriebener Vertrag braucht keinen neuen Link.": "A signed contract does not need a new link.",
  "einen Zugang mit der Rolle „Steuerberater“ an. Dieser sieht ausschließlich die Buchhaltung (nur lesend) und kann die Exporte und Belege hier selbst herunterladen.": "an account with the \"Accountant\" role. It sees accounting only (read-only) and can download the exports and receipts here itself.",
  "Einstellungen wurden gespeichert.": "Settings have been saved.",
  "Forderung ist wieder offen.": "Charge is open again.",
  "Forderung nicht gefunden.": "Charge not found.",
  "Forderung wurde als erlassen markiert.": "Charge has been marked as waived.",
  "Foto wird vorbereitet …": "Preparing photo …",
  "Für {anzahl} Ausgabe(n) liegt noch kein Beleg vor. Ohne Beleg kann der Steuerberater die Buchung in der Regel nicht anerkennen.": "{anzahl} expense(s) have no receipt yet. Without one your accountant usually cannot accept the transaction.",
  "Für die Bettzuweisung wird ein Mietbeginn benötigt.": "Assigning a bed requires a start date.",
  "Für diese IBAN gibt es bereits ein Konto.": "There is already an account with that IBAN.",
  "gelöst.": "instead.",
  "geöffnet {datum}": "opened {datum}",
  "Gesamtes Jahr {jahr}": "Whole year {jahr}",
  "Google Drive ist nicht konfiguriert.": "Google Drive is not configured.",
  "Gültig bis {datum}": "Valid until {datum}",
  "Höchstens 12 MB": "12 MB at most",
  "Im Titel steht kein Name.": "There is no name in the title.",
  "Im Zimmer wohnen noch Mieter. Bitte zuerst die Mietverhältnisse beenden.": "Tenants still live in this room. Please end the tenancies first.",
  "In der Ablage liegen eingescannte Mietverträge, die keinem Mieter zugeordnet werden konnten – oft weil der Name anders geschrieben ist.": "There are scanned rental contracts that could not be matched to a tenant - often because the name is spelled differently.",
  "Jede Kommune gibt ein eigenes Formular heraus. Wohnwerk baut es deshalb nicht nach, sondern füllt genau die Datei aus, die Sie hier hinterlegen – am Layout ändert sich dabei nichts.": "Every municipality issues its own form. Wohnwerk therefore does not rebuild it, but fills in exactly the file you store here - the layout stays untouched.",
  "Kein automatischer Versand – Vertragslinks werden zum Kopieren angezeigt.": "No automatic sending - contract links are shown for you to copy.",
  "Keine Buchungen gefunden": "No transactions found",
  "Keine Forderungen für {monat}": "No charges for {monat}",
  "Keine Treffer": "No matches",
  "Konto „{name}“ löschen?": "Delete account \"{name}\"?",
  "Kontoauszug und zugehörige Buchungen wurden entfernt.": "The bank statement and its transactions have been removed.",
  "Kopieren": "Copy",
  "Kopiert": "Copied",
  "Kostenposten „{name}“ wurde angelegt.": "Cost item \"{name}\" has been created.",
  "Kostenposten nicht gefunden.": "Cost item not found.",
  "Kostenposten wurde entfernt.": "Cost item has been removed.",
  "Kostenposten wurde gespeichert.": "Cost item has been saved.",
  "Kürzel {code}": "Code {code}",
  "Legen Sie einen Mieter an und weisen Sie ihm direkt ein Bett zu. Anschließend erhält er den Vertragslink.": "Add a tenant and assign them a bed right away. They then receive the contract link.",
  "Legen Sie unter": "Under",
  "Legen Sie zuerst ein Bankkonto an und laden Sie dann einen Kontoauszug hoch.": "Add a bank account first, then upload a statement.",
  "Legen Sie zuerst ein Objekt mit Zimmern und Betten an, damit Sie den Mieter zuweisen können.": "Add a property with rooms and beds first, so you can assign the tenant.",
  "Meldung #{nummer} ging raus, der Anhang aber nicht: {fehler}": "Report #{nummer} went out, but the attachment did not: {fehler}",
  "Mieter nicht gefunden.": "Tenant not found.",
  "Mieter und Vertragsentwurf wurden angelegt. Jetzt den Link an den Mieter senden.": "Tenant and draft contract have been created. Now send the link to the tenant.",
  "Mieter wurde angelegt.": "Tenant has been created.",
  "Mieter wurde gelöscht.": "Tenant has been deleted.",
  "Mieterdaten wurden gespeichert.": "Tenant details have been saved.",
  "Mietverhältnis nicht gefunden.": "Tenancy not found.",
  "Mietverhältnis wurde aktualisiert.": "Tenancy has been updated.",
  "Mindestens der Vorname muss angegeben werden.": "At least the first name is required.",
  "Mit der Freigabe wird der Vertragstext eingefroren und der Link aktiviert. Ist ein E-Mail-Versand eingerichtet, geht die Nachricht direkt an {email}.": "Issuing freezes the contract text and activates the link. If email sending is set up, the message goes straight to {email}.",
  "Nächster Monat: {monat}": "Next month: {monat}",
  "Name, E-Mail und ein Passwort mit mindestens 10 Zeichen sind nötig.": "Name, email and a password of at least 10 characters are required.",
  "Name, Straße, PLZ und Ort sind Pflichtfelder.": "Name, street, postcode and town are required.",
  "namentlich in der Liste unten": "listed by name below",
  "Neu": "New",
  "noch {betrag} offen": "{betrag} still open",
  "Noch kein Bankkonto": "No bank account yet",
  "Noch keine Mieter": "No tenants yet",
  "Noch keine Unterschrift.": "No signature yet.",
  "noch keinem Mieter zugeordnet": "not assigned to a tenant yet",
  "noch offen": "still open",
  "Notiz wurde hinzugefügt.": "Note has been added.",
  "Objekt „{name}“ mit allen Zimmern und Betten wirklich löschen?": "Really delete property \"{name}\" with all its rooms and beds?",
  "Objekt nicht gefunden.": "Property not found.",
  "Objekt wurde gelöscht.": "Property has been deleted.",
  "Objektdaten wurden gespeichert.": "Property details have been saved.",
  "Original nicht archiviert (Ablage nicht erreichbar)": "original not archived (storage not reachable)",
  "Passen Sie die Filter an oder laden Sie einen weiteren Kontoauszug hoch.": "Adjust the filters or upload another bank statement.",
  "Passen Sie Suche oder Filter an.": "Adjust your search or the filters.",
  "Passwort wurde geändert.": "Password has been changed.",
  "PDF wurde noch nicht abgelegt.": "The PDF has not been filed yet.",
  "Per Kontoauszug bestätigte Eingänge lassen sich hier nicht zurücknehmen – die Zuordnung dazu wird unter": "Payments confirmed from a bank statement cannot be undone here - unmatch them under",
  "Posten „{name}“ entfernen?": "Remove item \"{name}\"?",
  "Potenzial {betrag} pro Monat": "Potential {betrag} per month",
  "Scan „{name}“ endgültig löschen?": "Permanently delete scan \"{name}\"?",
  "Seite {seiten}": "Page {seiten}",
  "Ticket #{nummer} ist jetzt „{status}“.": "Ticket #{nummer} is now \"{status}\".",
  "Ticket #{nummer} wurde angelegt, der Anhang aber nicht gespeichert: {fehler}": "Ticket #{nummer} was created, but the attachment was not saved: {fehler}",
  "Ticket #{nummer} wurde angelegt.": "Ticket #{nummer} has been created.",
  "Ticket #{nummer} wurde gelöscht.": "Ticket #{nummer} has been deleted.",
  "Ticket nicht gefunden.": "Ticket not found.",
  "Ticket wurde gespeichert.": "Ticket has been saved.",
  "Unbekannte Art des Vordrucks.": "Unknown kind of form.",
  "Unterschrift erfasst.": "Signature captured.",
  "Versand über Resend aktiv (Absender {absender}).": "Sending via Resend is active (sender {absender}).",
  "Vertrag {nummer}": "Contract {nummer}",
  "Vertrag liegt in der Ablage und kann zugeordnet werden.": "The contract is unassigned and can be matched to a tenant.",
  "Vertrag nicht gefunden.": "Contract not found.",
  "Vertrag von {name} ist beendet.": "{name}'s contract has ended.",
  "Vertrag wurde als unterschrieben erfasst.": "The contract has been recorded as signed.",
  "Vertrag wurde storniert. Das Bett ist wieder frei.": "The contract has been cancelled. The bed is free again.",
  "Vertragsentwurf wurde angelegt.": "Draft contract has been created.",
  "von möglichen {betrag}": "of a possible {betrag}",
  "Vordruck „{name}“ wirklich entfernen?": "Really remove form \"{name}\"?",
  "Vordruck nicht gefunden.": "Form not found.",
  "Vordruck wurde entfernt.": "Form has been removed.",
  "Voriger Monat: {monat}": "Previous month: {monat}",
  "Zimmer „{name}“ mit allen Betten wirklich löschen?": "Really delete room \"{name}\" with all its beds?",
  "Zimmer nicht gefunden.": "Room not found.",
  "Zimmer wurde gelöscht.": "Room has been deleted.",
  "Zimmer wurde gespeichert.": "Room has been saved.",
  "zu – andernfalls legen Sie hier einen neuen Vertrag an.": "- otherwise create a new contract here.",
  "Zu diesem Mietverhältnis ist kein Mietvertrag hinterlegt. Liegt der unterschriebene Vertrag als Scan vor, ordnen Sie ihn in der": "There is no rental contract on file for this tenancy. If you have the signed contract as a scan, assign it in the",
  "Zugang für {name} wurde angelegt.": "Account for {name} has been created.",
  "Zugang wurde deaktiviert.": "Account has been deactivated.",
  "Zuordnung aufgehoben – der Vertrag liegt wieder in der Ablage.": "Unassigned - the contract is back in the unassigned list.",
  "Zuordnung der Formularfelder gespeichert.": "Form field mapping saved.",
  "Zuordnung wurde aufgehoben.": "The match has been removed.",

  // --- Zustand der Dokumentenablage ---------------------------------------
  "Als ehemalig markieren": "Mark as former",
  "Datenbank-Ablage nicht erreichbar: {grund}": "Database storage not reachable: {grund}",
  "Dokumente werden in der Supabase-Datenbank abgelegt ({anzahl} Dateien) – keine Einrichtung nötig.": "Documents are stored in the Supabase database ({anzahl} files) - no setup needed.",
  "Dokumente werden in Supabase Storage abgelegt (Bucket „{bucket}“).": "Documents are stored in Supabase Storage (bucket \"{bucket}\").",
  "Drive-Zugriff fehlgeschlagen: {grund}": "Drive access failed: {grund}",
  "Freigabe fehlgeschlagen: {grund}": "Sharing failed: {grund}",
  "Offene Forderungen: {betrag}": "Outstanding charges: {betrag}",
  "Ordner wurde für {email} freigegeben.": "The folder has been shared with {email}.",
  "Supabase Storage antwortet mit {status} – Bucket „{bucket}“ vorhanden und SUPABASE_SECRET_KEY gültig?": "Supabase Storage responded with {status} - does bucket \"{bucket}\" exist and is SUPABASE_SECRET_KEY valid?",
  "Supabase Storage nicht erreichbar: {grund}": "Supabase Storage not reachable: {grund}",
  "Verbunden mit Ordner „{ordner}“.": "Connected to folder \"{ordner}\".",
  "Wieder aktiv setzen": "Set active again",
  "Zugangsdaten vorhanden, aber der Drive-Client liess sich nicht initialisieren.": "Credentials are present, but the Drive client could not be initialised.",

  // --- Zahlungserinnerung -------------------------------------------------
  "Erinnerung kopieren (Albanisch)": "Copy reminder (Albanian)",
  "Gesamt offen: {betrag}": "Total outstanding: {betrag}",
  "Nachricht": "Message",
  "Nachricht an {name}": "Message to {name}",
  "Nachricht gesendet am {zeitpunkt}": "Message sent on {zeitpunkt}",
  "kopiert": "copied",
  "Zahlungserinnerung mit allen offenen Posten – zum Kopieren oder für WhatsApp": "Payment reminder with everything outstanding, to copy or send via WhatsApp",
  "alle offenen Monate und die Kaution in einer Nachricht": "all open months and the deposit in one message",
  "Text anzeigen": "Show text",
  "Kein WhatsApp-Link: Es ist keine Telefonnummer hinterlegt.": "No WhatsApp link: no phone number on file.",
  "Nummer eintragen": "Add a number",
  "Text der Nachricht": "Message text",
  "Der Browser hat die Zwischenablage verweigert – Text oben markieren und von Hand kopieren.": "The browser refused clipboard access. Select the text above and copy it by hand.",
  "Albanisch": "Albanian",
  "Bulgarisch": "Bulgarian",
  "Rumänisch": "Romanian",
  "Ungarisch": "Hungarian",
  "Englisch": "English",
  "{anzahl} Bewohner ohne Mietforderung für {monat}": "{anzahl} resident(s) without a rent charge for {monat}",
  "Vertragsentwurf, noch nicht versendet": "Contract draft, not sent yet",
  "Ein Entwurf bekommt seine Forderungen, sobald der Vertrag versendet ist.": "A draft gets its charges as soon as the contract has been sent.",
  "Mit Landesvorwahl, z. B. +49 151 2345678 – für den WhatsApp-Link bei den Mieteingängen.":
    "With country code, e.g. +49 151 2345678 - used for the WhatsApp link on rent payments.",

  // --- Unterkunft auf der Mieterseite ---------------------------------------
  "seit {datum}": "since {datum}",
  "bis {datum}": "until {datum}",
  "Ändern": "Change",
  "Bett zuweisen": "Assign a bed",
  "Diese Person hat noch keine Unterkunft. Objekt, Zimmer und Bett wählen – der Vertragsentwurf entsteht dabei.":
    "This person has no accommodation yet. Choose property, room and bed - the draft contract is created along the way.",

  // --- Kontaktliste ---------------------------------------------------------
  "Kontakte": "Contacts",
  "Name, Telefon und private E-Mail aller Mieter – direkt in der Zeile ändern. Nichts davon ist Pflicht.":
    "Name, phone and private email of every tenant - edit right in the row. None of it is required.",
  "Nur aktive Mieter": "Active tenants only",
  "Auch ehemalige Mieter": "Include former tenants",
  "{anzahl} von {gesamt} Mietern haben noch keine Telefonnummer – ohne sie gibt es bei den Mieteingängen keinen WhatsApp-Link.":
    "{anzahl} of {gesamt} tenants have no phone number yet - without one there is no WhatsApp link on rent payments.",
  "E-Mail privat": "Private email",
  "Kein Bett": "No bed",
  "Kontakt von {name} gespeichert.": "Contact details for {name} saved.",

  // --- Kautionen ------------------------------------------------------------
  "Kautionen": "Deposits",
  "Einmalig zum Einzug fällig. Hier steht für jeden Bewohner, ob die Kaution eingegangen ist, noch fehlt oder erst eingetragen werden muss.":
    "Due once at move-in. For every resident this shows whether the deposit has arrived, is still missing or has yet to be entered.",
  "Ohne Kaution": "No deposit",
  "Bewohner, bei denen noch kein Betrag eingetragen ist": "Residents with no amount entered yet",
  "Jeder Bewohner mit Bett erscheint hier – auch ohne vereinbarte Kaution.":
    "Every resident with a bed appears here, even without an agreed deposit.",
  "Keine Kaution eingetragen": "No deposit entered",
  "Keine Kaution vereinbart": "No deposit agreed",
  "Vertrag ohne Kaution": "Contract without a deposit",
  "Keine Kaution": "No deposit",
  "Vertrag ohne Kaution – es wird keine Kaution berechnet": "Contract without a deposit; no deposit will be charged",
  "„Keine Kaution“ zurücknehmen": "Undo \"no deposit\"",
  "Die Kaution ist schon bezahlt oder einem Kontoeingang zugeordnet – sie lässt sich nicht auf „keine Kaution“ setzen.":
    "The deposit is already paid or matched to a bank receipt. It cannot be set to \"no deposit\".",
  "Als „keine Kaution“ vermerkt. Es wird keine Kaution berechnet.": "Noted as \"no deposit\". No deposit will be charged.",
  "„Keine Kaution“ zurückgenommen – der Betrag kann jetzt eingetragen werden.": "\"No deposit\" undone. The amount can now be entered.",
  "Forderung fehlt": "Charge missing",
  "Forderung erzeugen": "Create charge",
  "Betrag rechts eintragen": "Enter the amount on the right",
  "Forderung noch nicht erzeugt": "Charge not created yet",
  "Kaution im Mietverhältnis eintragen und Forderung erzeugen": "Enter the deposit in the tenancy and create the charge",
  "Eintragen": "Enter",
  "Bitte einen Kautionsbetrag über 0,00 € eingeben.": "Please enter a deposit amount above €0.00.",
  "Kaution hinterlegt, Forderung erzeugt.": "Deposit saved, charge created.",
  "Kaution hinterlegt. Die Forderung entsteht, sobald der Vertrag versandt ist.":
    "Deposit saved. The charge is created once the contract has been sent.",
  "Kautionen gesamt": "Deposits in total",
  "{anzahl} Mietverhältnisse": "{anzahl} tenancies",
  "{anzahl} Kaution(en) fehlen": "{anzahl} deposit(s) missing",
  "Alle Kautionen sind eingegangen.": "All deposits have arrived.",
  "Keine Kautionen": "No deposits",
  "Einzug": "Move-in",

  // --- Zuordnung von Zahlungen --------------------------------------------
  "Buchung nicht gefunden.": "Transaction not found.",
  "Der Betrag muss größer als 0 sein.": "The amount must be greater than 0.",
  "Die Buchung ist bereits vollständig zugeordnet.": "The transaction is already fully matched.",
  "Die Mietforderung ist bereits ausgeglichen.": "The rent charge is already settled.",
  "Mietforderung nicht gefunden.": "Rent charge not found.",
  "Nur Zahlungseingänge lassen sich Mietforderungen zuordnen.": "Only incoming payments can be matched to rent charges.",
  "Zahlung wurde zugeordnet.": "Payment has been matched.",

  // --- Feldzuordnung der PDF-Vordrucke ------------------------------------
  "{anzahl} gesperrt": "{anzahl} blocked",
  "Arbeitgeber": "Employer",
  "Ausstellung": "Issue",
  "Ausstellungsort": "Place of issue",
  "Geburtsort": "Place of birth",
  "Heutiges Datum": "Today's date",
  "Mietbeginn / Einzugsdatum": "Start of tenancy / move-in date",
  "Mietverhältnis": "Tenancy",
  "Monatsmiete": "Monthly rent",
  "Ort und heutiges Datum": "Town and today's date",
  "PLZ und Ort": "Postcode and town",
  "unterschrieben {datum}": "signed {datum}",
  "Unterschrift (Bild)": "Signature (image)",
  "Vertragsnummer": "Contract number",
  "Vor- und Nachname": "First and last name",
  "{belegt}/{gesamt} Betten ·": "{belegt}/{gesamt} beds ·",
  "Zeitraum {von} bis {bis}": "Period {von} to {bis}",
  "{belegt} belegt · {frei} frei": "{belegt} occupied · {frei} free",

  // --- Buchungskategorien -------------------------------------------------
  // Der Wert steht so in der Datenbank; übersetzt wird nur die Anzeige.
  "Bankgebühren": "Bank charges",
  "Einrichtung / Möbel": "Furnishing / furniture",
  "Grundsteuer / Abgaben": "Property tax / levies",
  "Instandhaltung": "Maintenance",
  "Internet / Telefon": "Internet / phone",
  "Miete Einnahme": "Rent income",
  "Nebenkosten Einnahme": "Utilities income",
  "Objektmiete (Ausgabe)": "Property rent (expense)",
  "Reinigung": "Cleaning",
  "Strom / Gas / Wasser": "Electricity / gas / water",
  "Versicherung": "Insurance",
  "Verwaltung / Software": "Administration / software",
};
